### ISSUE TITLE
Compiler v120: Example project does not show notification

### ISSUE THREAD

**Issue by PhilLab** [mohabouje/WinToast#20]
My configuration: Windows 10, Visual Studio 2013 (v120), 64 bit

I compiled the example project (I changed the toolset from v140 to v120, maybe this is relevant?) and executed the example command
```
"WinToast Console Example.exe" --appname "Yolo" --aumi "My.Console.Example" --image "if_terminal_298878.png" --expirems 10000 --action Yes --action No --text "Do you want to try to take over the world?"
```
The notification did not appear and the console reported
```
Default App User Model Id: My.Console.Example
Default shell link path: C:\Users\PhilLab\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\
Default shell link file path: C:\Users\PhilLab\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Yolo.lnk
xml: <toast template="ToastGeneric" duration="long"><visual><binding template="ToastImageAndText01"><image id="1" src=""/><text id="1">Do you want to try to take over the world?</text></binding></visual><actions><action content="Yes" arguments="0"/><action content="No" arguments="1"/></actions></toast>
Error showing current toast
```

**Comment by dscho** [comment]
@PhilLab I think you hit the same problem as I did (and which led me to open #14): the first time the command-line tool runs, it creates the shortcut, but then *immediately* tries to show the toast. This somehow does not work most of the time.

In my tests, I had to wait 5 seconds and then simply try again. Does that work for you?

To work around the underlying issue, I introduced #17, so that the shortcut could be created early. That way, scripted users could create the shortcut long before they want to show a toast.

BTW the example also exits with an exit code indicating that there was an error showing the toast (5), to which your script could react.

**Comment by PhilLab** [comment]
@dscho I tried the call serveral times in a row (as I understood your recommendation, this should've worked) but nothing was shown. The Yolo.lnk file is present in the given folder. How can one be sure that the link file is not written exactly *while* the toast call is issued?

**Comment by PhilLab** [comment]
Okay... I found it. After setting the /DEBUG flag in the solution and attaching a debugger, I found out that the ``IToastFailedEventArgs`` translate to
> Settings prevent the notification from being delivered

and yes, the system settings were set to disallow notifications:

![image](https://user-images.githubusercontent.com/1710255/33027637-f69af378-ce13-11e7-843a-46e16e5d0979.png)

Switched them back on again and it works :-) Thank you!

**Comment by dscho** [comment]
Ah, I did not think of that. Great that you found out!
