### ISSUE TITLE
Handler not working?

### ISSUE THREAD

**Issue by HJfod** [mohabouje/WinToast#56]
I'm fairly new to C++ and I want to make a simple console application that runs in the background and sends a notification every now and then. For some reason VS Code keeps giving me this error? I can't seem to find a solution online, if someone could help that'd be appreciated!

![image](https://user-images.githubusercontent.com/60038575/95045131-ebe91600-06e9-11eb-8e96-0cba4e5d55e8.png)

**Comment by xavery** [comment]
Don't post screenshots of code, both the code and error in text form would suffice.

Anyhow, this error occurs because you seem to have only implemented `toastActivated()`, while `toastActivated(int actionIndex)` is also declared as abstract in `IWinToastHandler`, which means that your class must provide an implementation of it as well.
