### ISSUE TITLE
createShellLinkHelper disabled

### ISSUE THREAD

**Issue by lollita** [mohabouje/WinToast#60]
Why "create a Shell Link for the app"?
I disable it and work however.

**Comment by agashlin** [comment]
Coincidentally, I am just now working on a PR to allow this to be disabled (in the process of fixing [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1672957)). The shortcut is needed because a custom model (e.g. specifying action buttons) can't be used if there isn't a shortcut with the same AUMI as the app showing the notification. In my case we'd rather not show the notification instead of creating a useless shortcut to the notification app (which otherwise has no UI), so it is helpful to disable it.

**Comment by agashlin** [comment]
The [documentation](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/hh802762(v=vs.85)) is actually a bit stronger, it says "Without a valid shortcut installed in the Start screen or in All Programs, you cannot raise a toast notification from a desktop app," but this doesn't seem to prevent showing *any* notification, just one with a custom model. This is why the shortcut was added along with the commit (8271b5bf0be1a1246735d712df1a24ee4e86f817) that added custom abstract models.

**Comment by lollita** [comment]
Thanks for the reply.
I think an option would be more appropriate to avoid creating it when not using custom templates.
