### ISSUE TITLE
Can not hide app icon, which shows the process name

### ISSUE THREAD

**Issue by HsiuWei** [mohabouje/WinToast#69]
I am using template, ImageAndText02, but the result is different from README.

I keep seeing the process name showing above of the toast. Is there a way to hide it? Thanks!
![3](https://user-images.githubusercontent.com/15167724/118100904-95735100-b409-11eb-8e90-63aac3e1497c.png)

**Comment by liruofeng** [comment]
@HsiuWei , I think this is the default behavior of  Win10  OS, so it is difficult to hide it

**Comment by HsiuWei** [comment]
I see. On the other hand, my another computer does not have this behavior. Is it possible to tell the difference between Win10 OS?

**Comment by ChristianGalla** [comment]
2 times a year there is a feature upgrade for Windows. Among other things, changes to the toast notifications may be included. Because not all Computers are updated immediately (for example because of not yet compatible hardware / drivers), it is possible to observe different behaviors.

You can check your current version using [winver](https://support.microsoft.com/en-us/windows/which-version-of-windows-operating-system-am-i-running-628bec99-476a-2c13-5296-9dd081cdd808).

For example if you see Windows 10 version 2004, you are using the version that was released in April 2020.

You can manually update to a newer version using Windows update.
